### PR TITLE
Ensure AWS secret variables are defined

### PR DESCRIPTION
**Pull request by haavard**
This prevents failures due to the nounset option being enabled.

Fixes https://github.com/balena-io/scripts/issues/7

### CODE REVIEW

**Comment by haavard** [comment]
Thanks -- I've rebased the commit.

**Comment by thundron** [comment]
@resin-ci retest

**Comment by thundron** [comment]
@haavard Sorry just noticed that the commit is missing the footer tag "Change-type", you can set it to "patch" for this one (e.g. "Change-type: patch"), the other tags are "minor" and "major"

**Comment by haavard** [comment]
Done!

**Comment by thundron** [comment]
@resin-ci retest

**Pull request merged**
