### PR TITLE
Run Xvfb with "-extension GLX" to prevent electron-mocha from segfaulting

### PR DESCRIPTION
**Pull request by zvin**
Change-type: patch

### CODE REVIEW

**Comment by nazrhom** [comment]
@zvin why not promote the XVFB_ARGS to a proper variable, or just define the env var at call-site to add the extension?

**Comment by zvin** [comment]
@nazrhom it's not used anywhere else

**Comment by nazrhom** [comment]
@zvin right, we still might use it in the future though. Unless we think that we definitely don't want to pass more options, and that every electron app should have this parameter

**Comment by zvin** [comment]
We'll make it a variable in the future then.
I don't think we will pass more options.
Every app should have this option, electron on Xvfb without this option segfaults (at least electron 7 on ubuntu 18.04)

**Pull request merged**
